/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Product.View;

import Product.Modle.Product;
import Product.Service.ProductService;
import static Product.View.AddProduct.isNumeric;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class EditProduct extends javax.swing.JFrame {
    private Product product;
    ProductService productService;
    public EditProduct(int id) {
        product = new Product();
        productService = new ProductService();
        product = productService.getProductById(id);
        initComponents();
        id_product.setText(String.valueOf(product.getId_product()));
        nameProduct.setText(product.getTen_product());
        String color = product.getMau();
        System.out.println(color);        
        if(color != null) {
            if(color.equals("Red")){
                colorUpdate.setSelectedIndex(0);
            }
             if(color.equals("Blue")){
                colorUpdate.setSelectedIndex(1);
            }
              if(color.equals("Black")){
                colorUpdate.setSelectedIndex(2);
            }
               if(color.equals("While")){
                colorUpdate.setSelectedIndex(3);
            }
                if(color.equals("Yellow")){
                colorUpdate.setSelectedIndex(4);
            }
        }
        String gioiTinh = product.getGioiTinh();
        if(gioiTinh != null){
            if(gioiTinh.equals("Nam"))
                namUpdate.setSelected(true);
            if(gioiTinh.equals("Nu"))
                nuUpdate.setSelected(true);
        }
        String category = product.getCategory();
        if(category != null) {
            if(category.equals("Casual Shoes")){
            categoryUpdate.setSelectedIndex(0);
            }
             if(category.equals("Dress Shoes")){
            categoryUpdate.setSelectedIndex(1);
            }
              if(category.equals("Boots")){
            categoryUpdate.setSelectedIndex(2);
            }
        }
        int size = product.getSize();
        System.out.println(size);
        thanhSizeUpdate.setValue(size);
        soLuongUpdate.setValue(product.getSoLuongDat());
        priceUpdate.setText(product.getGia());
        informationUpdate.setText(product.getThongTin());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_List = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        information_txt = new javax.swing.JTextArea();
        category_combobox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sizeday = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Giaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        color_colocompo = new javax.swing.JComboBox<>();
        giaca = new javax.swing.JLabel();
        namRadio = new javax.swing.JRadioButton();
        namePro = new javax.swing.JTextField();
        NuRadio = new javax.swing.JRadioButton();
        Save = new javax.swing.JButton();
        thanhsize = new javax.swing.JSlider();
        Reset = new javax.swing.JButton();
        soluong = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        backUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        informationUpdate = new javax.swing.JTextArea();
        categoryUpdate = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sizeJslider = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        priceUpdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        colorUpdate = new javax.swing.JComboBox<>();
        giaca1 = new javax.swing.JLabel();
        namUpdate = new javax.swing.JRadioButton();
        nameProduct = new javax.swing.JTextField();
        nuUpdate = new javax.swing.JRadioButton();
        saveUpdate = new javax.swing.JButton();
        thanhSizeUpdate = new javax.swing.JSlider();
        resetUpdate = new javax.swing.JButton();
        soLuongUpdate = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        id_product = new javax.swing.JTextField();

        Back_List.setBackground(new java.awt.Color(255, 153, 51));
        Back_List.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        Back_List.setText("Back");
        Back_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ListActionPerformed(evt);
            }
        });

        information_txt.setColumns(20);
        information_txt.setRows(5);
        jScrollPane1.setViewportView(information_txt);

        category_combobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casual Shoes", "Dress Shoes", "Boots" }));
        category_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboboxActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADD PRODUCT");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Netbean_Java\\Image_Icon\\newProduct.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Category: ");

        sizeday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name Product:");

        Giaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Color:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("NumBer :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Size:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Information:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("GenDer:");

        color_colocompo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color_colocompo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Blue", "Black", "While", "Yellow" }));
        color_colocompo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_colocompoActionPerformed(evt);
            }
        });

        giaca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        giaca.setText("Price:");

        namRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namRadio.setText("Boy");
        namRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioActionPerformed(evt);
            }
        });

        namePro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        NuRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NuRadio.setText("Girl");

        Save.setBackground(new java.awt.Color(255, 153, 0));
        Save.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        Save.setText("Add");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        thanhsize.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        thanhsize.setMajorTickSpacing(2);
        thanhsize.setMaximum(50);
        thanhsize.setMinimum(35);
        thanhsize.setMinorTickSpacing(1);
        thanhsize.setPaintLabels(true);
        thanhsize.setPaintTicks(true);
        thanhsize.setValue(30);
        thanhsize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thanhsizeStateChanged(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(255, 153, 51));
        Reset.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        soluong.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        soluong.setMaximumSize(new java.awt.Dimension(10, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        backUpdate.setBackground(new java.awt.Color(255, 153, 51));
        backUpdate.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        backUpdate.setText("Back");
        backUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUpdateActionPerformed(evt);
            }
        });

        informationUpdate.setColumns(20);
        informationUpdate.setRows(5);
        jScrollPane2.setViewportView(informationUpdate);

        categoryUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casual Shoes", "Dress Shoes", "Boots" }));
        categoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryUpdateActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("UPDATE PRODUCT");

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Netbean_Java\\Image_Icon\\newProduct.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Category: ");

        sizeJslider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Name Product:");

        priceUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Color:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("NumBer :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Size:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Information:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("GenDer:");

        colorUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colorUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red", "Blue", "Black", "While", "Yellow" }));
        colorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorUpdateActionPerformed(evt);
            }
        });

        giaca1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        giaca1.setText("Price:");

        buttonGroup1.add(namUpdate);
        namUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namUpdate.setText("Boy");
        namUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namUpdateActionPerformed(evt);
            }
        });

        nameProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(nuUpdate);
        nuUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuUpdate.setText("Girl");

        saveUpdate.setBackground(new java.awt.Color(255, 153, 0));
        saveUpdate.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        saveUpdate.setText("Save");
        saveUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateActionPerformed(evt);
            }
        });

        thanhSizeUpdate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        thanhSizeUpdate.setMajorTickSpacing(2);
        thanhSizeUpdate.setMaximum(50);
        thanhSizeUpdate.setMinimum(35);
        thanhSizeUpdate.setMinorTickSpacing(1);
        thanhSizeUpdate.setPaintLabels(true);
        thanhSizeUpdate.setPaintTicks(true);
        thanhSizeUpdate.setValue(35);
        thanhSizeUpdate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thanhSizeUpdateStateChanged(evt);
            }
        });

        resetUpdate.setBackground(new java.awt.Color(255, 153, 51));
        resetUpdate.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        resetUpdate.setText("Reset");
        resetUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUpdateActionPerformed(evt);
            }
        });

        soLuongUpdate.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        soLuongUpdate.setMaximumSize(new java.awt.Dimension(10, 1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("ID Poduct");

        id_product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(backUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(resetUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(saveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(namUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nuUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(colorUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(id_product, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(giaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sizeJslider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(soLuongUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thanhSizeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(priceUpdate)
                                        .addGap(20, 20, 20))
                                    .addComponent(categoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_product, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colorUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuUpdate)
                            .addComponent(namUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thanhSizeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sizeJslider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soLuongUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceUpdate)
                            .addComponent(giaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ListActionPerformed
        ListProduct l = new ListProduct();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ListActionPerformed

    private void category_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_comboboxActionPerformed

    private void color_colocompoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_colocompoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color_colocompoActionPerformed

    private void namRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

    }//GEN-LAST:event_SaveActionPerformed

    private void thanhsizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thanhsizeStateChanged
        sizeday.setText("" + thanhsize.getValue());
    }//GEN-LAST:event_thanhsizeStateChanged

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        namePro.setText("");
        information_txt.setText("");
        soluong.setValue("");
        Giaca.setText("");

    }//GEN-LAST:event_ResetActionPerformed

    private void backUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUpdateActionPerformed
        ListProduct l = new ListProduct();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backUpdateActionPerformed

    private void categoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryUpdateActionPerformed

    private void colorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorUpdateActionPerformed

    }//GEN-LAST:event_colorUpdateActionPerformed

    private void namUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namUpdateActionPerformed
 
    }//GEN-LAST:event_namUpdateActionPerformed

    private void saveUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateActionPerformed
    String namProduct = nameProduct.getText();
    String Price = priceUpdate.getText();
    String Thongtin = informationUpdate.getText();
    StringBuilder sb = new StringBuilder();
    if(namProduct.equals(""))
        sb.append("Product Name not empty");
    if(Price.equals(""))
        sb.append("\nPrice not empty");
    if(Thongtin.equals(""))
        sb.append("\nInformation not emty");
    if(namUpdate.isSelected()==false && nuUpdate.isSelected()==false)
        sb.append("\nGender not empty");
    if(isNumeric(priceUpdate.getText())==false){
        sb.append("\nPrice cannot be a string ");
    }
    if(sb.length() > 0)
    {
         JOptionPane.showMessageDialog(this,sb.toString(),"Errol Messeger",JOptionPane.ERROR_MESSAGE);
         return;
    }                                    
   
    String gender = "";
    if(namUpdate.isSelected())
        gender += "Nam";
    if(nuUpdate.isSelected())
        gender += "Nu";
    int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Create a new product? " );
    if(confirm == JOptionPane.YES_OPTION){
        product.setCategory(categoryUpdate.getSelectedItem().toString());
        product.setTen_product(nameProduct.getText());
        product.setMau(colorUpdate.getSelectedItem().toString());
        product.setGioiTinh(gender);
        product.setSize(thanhSizeUpdate.getValue());
        product.setSoLuongDat((int) soLuongUpdate.getValue());
        product.setGia(priceUpdate.getText());
        product.setThongTin(informationUpdate.getText());
        productService.updateProduct(product);
        JOptionPane.showMessageDialog(this, "Successful new creation");
        ListProduct li = new ListProduct();
        li.setVisible(true);
        this.dispose();
    }
         
    }//GEN-LAST:event_saveUpdateActionPerformed

    private void thanhSizeUpdateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thanhSizeUpdateStateChanged
        sizeJslider.setText("" + thanhSizeUpdate.getValue());
    }//GEN-LAST:event_thanhSizeUpdateStateChanged

    private void resetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetUpdateActionPerformed

    }//GEN-LAST:event_resetUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditProduct().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_List;
    private javax.swing.JTextField Giaca;
    private javax.swing.JRadioButton NuRadio;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Save;
    private javax.swing.JButton backUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoryUpdate;
    private javax.swing.JComboBox<String> category_combobox;
    private javax.swing.JComboBox<String> colorUpdate;
    private javax.swing.JComboBox<String> color_colocompo;
    private javax.swing.JLabel giaca;
    private javax.swing.JLabel giaca1;
    private javax.swing.JTextField id_product;
    private javax.swing.JTextArea informationUpdate;
    private javax.swing.JTextArea information_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton namRadio;
    private javax.swing.JRadioButton namUpdate;
    private javax.swing.JTextField namePro;
    private javax.swing.JTextField nameProduct;
    private javax.swing.JRadioButton nuUpdate;
    private javax.swing.JTextField priceUpdate;
    private javax.swing.JButton resetUpdate;
    private javax.swing.JButton saveUpdate;
    private javax.swing.JLabel sizeJslider;
    private javax.swing.JLabel sizeday;
    private javax.swing.JSpinner soLuongUpdate;
    private javax.swing.JSpinner soluong;
    private javax.swing.JSlider thanhSizeUpdate;
    private javax.swing.JSlider thanhsize;
    // End of variables declaration//GEN-END:variables
}
